language: cpp
env:
  - VALGRIND_VERSION=tags/VALGRIND_3_12_0
  - VALGRIND_VERSION=trunk
matrix:
  allow_failures:
    - env: VALGRIND_VERSION=trunk
install:
  - make -f travis.mk download-valgrind
  - make -f travis.mk patch-valgrind
  - make -f travis.mk configure
  - make -f travis.mk build
script:
  - make -f travis.mk check-install
  - make -f travis.mk check || make -f travis.mk check-error
